---
version: 2
updates:
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
      timezone: Europe/Copenhagen
    reviewers:
      - "reload/developers"
    ignore:
      - dependency-name: "php"
      - dependency-name: "docker.io/library/php"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      timezone: Europe/Copenhagen
    reviewers:
      - "reload/developers"
